### ISSUE TITLE
[feature request] "Cold" parse method

### ISSUE THREAD

**Issue by Andarist** [lukeed/sade#12]
I'd like to be able to parse argv just to get parsed options without actually executing registered commands. IMHO it's slightly unintuitive API that `parse` method also executes stuff, I'd argue that it should only parse and nothing else, but ofc that would be a breaking change, so I'm merely asking if there is a possibility to add a "cold" version of this method?

I can work on it if we figure out what it should be called :p

reference https://github.com/developit/microbundle/pull/62/files#r163778889

**Comment by lukeed** [comment]
Hey~! Sorry for the long delay -- I've been tied up with work.

I'm not entirely sure I understand what you're after. You just want the final `args` output? Are you okay with letting the `argv.help`, `argv.version`, and `cmd === void 0` checks take place first?

I'd probably want to call this `opts.noop` or `opts.norun` & then return a `{ args, handler }` object so that the user has all necessary pieces to continue execution later on at his/her choosing.

**Comment by Andarist** [comment]
> You just want the final args output? 

Yeah, `args` is what im looking for.

> Are you okay with letting the argv.help, argv.version, and cmd === void 0 checks take place first?

Somewhat - I can live with them (i don't plan to test those things), but ideally this would be split too.

> I'd probably want to call this opts.noop or opts.norun & then return a { args, handler } object so that the user has all necessary pieces to continue execution later on at his/her choosing.

I think this should solve my issue. 👍

**Comment by olstenlarck** [comment]
Yeah. Probably renaming current `.parse` to `.run` and the new `.parse` to be that cold parse which just return args and handler.

**Comment by lukeed** [comment]
It's named `parse` because it follows what _every_ other major CLI builder does: commander, caporal, vorpal, etc.

I'll make this change now. Decided to call it `opts.lazy` 😆

**Comment by lukeed** [comment]
I feel it's best to allow the same validations to take place before returning the parsed values. Changing the _moment_ in time when the `handler` runs shouldn't change the input or the internal checks IMO. 

Conditionally validating would mean deeper if-else-blocks and/or changing the logic entirely & I'd very much like to avoid that. The validations & early returns are placed methodically for proper juggling.

Let me know what you think~!

**Comment by Andarist** [comment]
Cool, thanks for this 🎉 Gonna remove my hacks from `microbundle` later thanks to this.
