### ISSUE TITLE
Default help

### ISSUE THREAD

**Issue by jsumners** [lukeed/sade#16]
Given:

```js
const prog = sade('greet');
 
prog.command('hello');
//=> only runs if :: `$ greet hello`
 
// $ greet
//=> error: No command specified.
 
prog.command('howdy', '', { default:true });
//=> runs as `$ greet` OR `$ greet howdy`
 
// $ greet
//=> runs 'howdy' handler
 
// $ greet foobar
//=> error: Invalid command
```

I would like to be able to specify that `greet -h` be equivalent to `greet howdy -h`.

I like the simple API of `sade` for describing CLI options. But almost every time I turn to this module for parsing such options, it's not for an interface that requires commands. I just need to supply options on the application itself. Defining a default command, albeit unintuitive, is an easy to way to do that. But it makes it difficult to get to the real "help" output.

**Comment by lukeed** [comment]
Hey~! I've thought about that before, but here's the issue: You'll never see the global help menu. 

This is hugely problematic when you have multiple commands, and need some kind of roadmap to navigate between them (and list them).

The only suggestions I can think of are (1) to add your own `help` command that calls the underlying `help()` with a name if not provided; and (2) to mutate the instance once it's been created:

```js
const prog = sade('greet').command('howdy', '', { default:true });

// Save the original Sade.help
let old = prog.help;
// Overwrite it w/ default (not global) fallback
prog.help = str => old.call(prog, str || 'howdy');
```

**Comment by jsumners** [comment]
That's what I'm saying: in this case there isn't even a need for a single command, so multiple commands will never be an issue. `greet howdy -h` **is** the main help.

But I've discovered the `args` module, based on `mri`, that does what I need. It's not quite as simple, but close enough.

**Comment by lukeed** [comment]
Cool~! Yeah, Sade is made for my CLIs with multiple commands. I find that if I only need 1 command, I can get by with just `mri` alone. 

Didn't know `args` shifted to using `mri` -- thanks for sharing & glad you found something that suits your needs 😄
