### ISSUE TITLE
What about required thing for some option? Possible?

### ISSUE THREAD

**Issue by olstenlarck** [lukeed/sade#18]
Didn't even tried, but it's not documented anyway, so this issue could be used for such PR.

I'm talking about somehting like

```
mycli cmd --registry <url> --token=<authToken>
```

In above, `<url>` is required for the `registry` option so it should throw with _"Insufficient arguments for that option"_ or something like that. To be the same as when there is required args for some command.

As i looked over the source code before some days, i didn't noticed that it is possible, because of the simple parsing in `$.parse` utility, so.

**Comment by lukeed** [comment]
Sade only enforces required values for positional arguments, not option flags.

This is user-land code, and `opts.lazy` makes this easy to do.
