### ISSUE TITLE
Rename the `this.name` to something other

### ISSUE THREAD

**Issue by tunnckoCore** [lukeed/sade#24]
Because I need to do some weird stuff like this

```js
const programName = this.name;
delete this.name;

// where `this` is the `prog` which is the "instance" of calling sade()
const handler = Object.assign(taskObj.handler, this);

// ! restore, because the help() needs it
this.name = programName;

return handler;
```

The case. I override a bit the `.action` method, for few reasons. And in this method I have above code, because I need to return the handler function and I where I use it I need also access to the "instance".

And in general, just "name" isn't that good. Probably `this.programName` makes more sense.

**Comment by lukeed** [comment]
You should never be relying on or trying to modify a library's internals... especially since I don't export the `class` directly haha.. almost like it was intentionally out of reach 😉 

What are you doing?

**Comment by tunnckoCore** [comment]
Yes, of course :laughing: That's why I still don't like that you just don't export a class. It would be a whole lot easier and I wouldn't have needed the tons of workaround that I encounter from time to time.

[It's here.](https://github.com/tunnckoCoreHQ/hela/blob/v3-next/packages/hela-core/src/index.js#L93-L103) The thing is that I must return a function. This `action()` override was doing a bit more, and now I'm thinking that it's needless if it stays that way. It used to be bigger since I wanted to make it support passing string instead of function, which would mean pass that string to `execa` - just a shortcut for `.action((argv) => execa('you cmd', argv))`. Also used to do to detect if the function retuns a string or array of strings, in this case - same thing, wrapping with `execa`.

Anyway, the thing is that I finally decided not to do those things. So the only reason I'm overriding the `action()` method is because I need from the return to ahve access to the "instance" too, so I can get the `this.tree` of commands. Because basically, [I'm merging them inside another instance](https://github.com/tunnckoCoreHQ/hela/blob/v3-next/packages/hela-cli/src/index.js#L63-L67). Where `taskValue` is actually the return of `action()` which is the handler function.

It would be easier if I just return an object from the `action()` but it's not possible, because other needs. For example

```js
const prog = sade()

const build = prog
  .command('build [src]', 'some building process')
  .action((src, argv) => {
    console.log('building', src, 'to ./dist/');
  })

build('pkg/foo/src', { foo: 'bar' })
```

**Comment by lukeed** [comment]
Lol, do you not see though that I'd be having to field more requests like this?

Also, very odd request I must say. Why does the upstream dependency need to change its internals? You should change your own internal names, no? The "you should not be using `name` key" argument applies equally to you

**Comment by tunnckoCore** [comment]
The thing is that I cannot and don't have anything to change. It's because the upstream dependency (kind of) breaks the downstream one. :D 

Anyway, I have the workaround, it's just ugly and needless if you change a few characters which are used internally in Sade, anyway, to generate the help.

And it basically isn't because of me or you, it's because `function`s has special property `.name` that you cannot override and error is thrown. Even if you don't want to do that you may get broken when merging things like this.

The `this.name` is a perfect candidate to be "private" - whether with typescript, underscore, or just renaming to some more hard to access the property, or at least something that cannot break anything no matter what's the case. That's just basic rule in general, isn't it?

**Comment by lukeed** [comment]
If you could extend Sade you'd still have this problem since the help text is built outside of the class, and that utility is passed the value. All it does it allow devs to manipulate the class in unforseen ways and then ping me when stuff breaks. No thanks, it does what it does 

Really what you should have done here is initialize a singleton Sade instance and then exposed your own API that interfaced with the Sade instance privately. Would have worked just fine based on your description, and not been "ugly" - using it would have appeared like any other library usage.

---

I will take a look at this tomorrow. There are quite a few dependents now so I have to look thru some of them to see if any are reading the program `name` too.

**Comment by tunnckoCore** [comment]
Exactly, that's again about design architecture problem of Sade. If it wasn't doing 
a few things outside the class none of these issues would exist.

> Really what you should have done here is initialize a singleton Sade instance and then exposed your own API that interfaced with the Sade instance privately.

Of course, I could create my own class or function and just replicate/mirror all the methods of Sade (like below), but that approach is unreliable and not future proof if Sade changes something (which probably won't happen or won't be so drastic, but still). Also, increases mine codebase unnecessarily and not because of some sane reason, but just because Sade wants to be closed for extending. Hence, the "O" in SOLID principles.

```js
class Hela {
  constructor() {
    this.prog = sade('hela').version('3.0.0')
  }
  option(...args) {
    return this.prog.option(...args);
  }
  // and so on...
}
```

> I will take a look at this tomorrow. There are quite a few dependents now so I have to look thru some of them to see if any are reading the program name too.

Cool, thanks. :)
