### ISSUE TITLE
Feature request: global/universal actions

### ISSUE THREAD

**Issue by arxpoetica** [lukeed/sade#33]
These might better be defined as 'hooks'.

I spent a while trying to create my own prehook on actions, something that would get run against every action. Something like the following:

```js
old_action = prog.action.bind(prog);
prog.action = function () {
    always_gets_called_on_every_action();
    return old_action.apply(prog, arguments)
}
```

The problem is there's still no way to get at the `opts` argument in this `prog.action` overwrite, which is what I need.

Use case: change the config file for *every* action (`-c, --config`) _without **manually** baking it into every action_.

I decided to stop wasting time on this and make hooks or something like that an actual feature request, or at least a point of conversation.

Thanks.

**Comment by tunnckoCore** [comment]
I guess, make a factory? [Something like that.](https://github.com/tunnckoCore/opensource/blob/master/%40hela/dev/src/index.js#L50)

But it can be a better way. I don't completely understand your use case. Example?

You can make it top-level `prog.option()`? So every command will have it, but I'm guessing that you want to have some default for `--config` based on what command is called, right? Like `prog build` will have `--config ./build.config.js`, the `prog bundle` will have `--config ./bundle.config.js` as default?

**Comment by tunnckoCore** [comment]
Or try 

```js
const prog = sade('my-cli');

const myPreHook = () => {
  console.log('on every action');
};

Object.assign(prog, {
  action(fn) {
    const name = this.curr || '__default__';
    this.tree[name].handler = async (...args) => {
      myPreHook();
      return fn.apply(this, args);
    };
  }
});

// when you later define .action() it will work as you expect
prog.command('foo', 'Call foo').action(() => {
  console.log('the foo command');
});

prog.command('bar', 'Call bar').action(() => {
  console.log('the bar command');
});
```

Coded at the github comment. Alsmost sure it will work.

**Comment by lukeed** [comment]
I would do something like this:

> Note: I think dealing with explicit function primitives for CLI composition is always the way to go

```js
// utils.js
/**
 * Wrap a command's action handler with some common logic
 * @param  {Function} action  Your _true_ `action` handler
 * @return {Function}               The wrapped `action` handler
 */
exports.wrapper = function (action) {
  return function () {
    always_gets_called_on_every_action();
    action.apply(action, arguments);
  };
}


// build.js
const { wrapper } = require('./utils');

module.exports = wrapper(
  function (dir, opts={}) {
    console.log('build with "%s"', dir, opts);
  }
);


// deploy.js
const { wrapper } = require('./utils');

module.exports = wrapper(
  function (dir, opts={}) {
    console.log('deploy with "%s"', dir, opts);
  }
);


// bin.js
const sade = require('sade');
const build = require('./build');
const deploy = require('./deploy');

sade('foobar')
  // .version('1.0.5')
  .command('build')
  .action(build)

  .command('deploy')
  .action(deploy)
```

That should be fine, and allows you the flexibility to change your mind going forward should you find that you didn't want something on **every** action. This allows you to define it in one location & attach it only where truly needed.

**Comment by lukeed** [comment]
Same idea as @tunnckoCore presented above (hello & thank you 😆) just in a slightly different organization

**Comment by tunnckoCore** [comment]
Yea, kinda of like yours more.

**Comment by tunnckoCore** [comment]
Actually. I think it's basically the same as the author's one, so it's probably possible to have the same problem with missing `options` (argv).

**Comment by lukeed** [comment]
You'd define a global `.option('-c, --config')` and presumably handle it within `always_gets_called_on_every_action`. Since `opts` is always last, it's easy.

```js
exports.wrapper = function (action) {
  return function (...args) {
    const len = args.length;
    always_gets_called_on_every_action(args[len - 1]);
    action.apply(action, args);
  };
}

**Comment by arxpoetica** [comment]
You guys are on fire—let me get back to you if this works...

**Comment by arxpoetica** [comment]
p.s. I tried `Object.assign(prog, { action(fn) { ... })` but:

> [Properties on the prototype chain...cannot be copied](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Properties_on_the_prototype_chain_and_non-enumerable_properties_cannot_be_copied)

**Comment by tunnckoCore** [comment]
But it's working right?

It's [done that way on `@hela/core`](https://github.com/tunnckoCore/hela/blob/next/%40hela/core/src/index.js#L59-L63) (which i'm rewriting now) and it's okay for a whole year, haha.

**Comment by lukeed** [comment]
If you wanted to do the `prog.action` route, it'd have to look like this:

```js
// save the old
const add_action = prog.action.bind(prog);

prog.action = function (handler) {
  add_action(
    // use the same `wrapper` util before
    // because it actually wraps the handler
    wrapper(handler)
  );
}
```

What you had modified `sade`'s construct. All that method does is build the tree, but what you (originally) showed was trying to execute/wrap the handler on initialization

**Comment by arxpoetica** [comment]
@tunnckoCore 
> But it's working right?
I couldn't get `Object.assign` to work, no, but I don't have that code anymore to really compare notes...

Regardless...

@lukeed your `wrapper` suggestion worked great. Still trying to wrap my mind around it (no pun intended), but it's a working solution, so closing.
