### ISSUE TITLE
[Feature Request] Ability to hide "For more info, run any command with `--help` flag"

### ISSUE THREAD

**Issue by vasanthdeveloper** [lukeed/sade#40]
Here is a cli I am working with 👇 

![Screenshot 2020-06-27 at 1 13 07 PM](https://user-images.githubusercontent.com/24322511/85917473-f6d51480-b877-11ea-8333-15e257a632c2.png)

For every command, I am adding, `sade` creates an additional line showing how to use the `--help` flag. When more commands are added, this creates a longer help message.

Please add the ability to disable this section. For a cli with a lot of commands, terminal spaces is not wasted.

**Comment by lukeed** [comment]
It's a limited section :) https://github.com/lukeed/sade/blob/master/lib/utils.js#L62

It's just enough examples so that your users know it applies generally

**Comment by vasanthdeveloper** [comment]
So, only two examples show up? 🤔

**Comment by lukeed** [comment]
Yes a maximum of two

**Comment by vasanthdeveloper** [comment]
Also, one quick question @lukeed 😀 
Can I contribute colored output? I have developed a custom argument parser https://github.com/vasanthdeveloper/varna
But unable to maintain it.

**Comment by lukeed** [comment]
Sorry I'm not sure what you're asking/suggesting

**Comment by vasanthdeveloper** [comment]
Can I contribute colored output to `sade`'s help message?

**Comment by lukeed** [comment]
Oh, no thank you. It's plain intentionally, because everyone has different ideas for what should/shouldn't be there. Better to be consistent and not visually annoying as the baseline
