### ISSUE TITLE
TypeError: prog.help is not a function

### ISSUE THREAD

**Issue by fregante** [lukeed/sade#43]
How can I call `prog.help()`? Here's a shortened example

```js
#!/usr/bin/env node
'use strict';
const sade = require('sade');
const ghat = require('./lib');
const pkg = require('./package.json');

const prog = sade(pkg.name + ' <source>', true)
	.version(pkg.version)
	.describe(pkg.description)
	.action(async (source, options) => {
		try {
			await ghat(source, options);
		} catch (error) {
			if (error instanceof ghat.InputError) {
				console.error('❌', error.message);
				prog.help();
			} else {
				throw error;
			}
		}
	})
	.parse(process.argv);
```

That throws with

```
TypeError: prog.help is not a function
```

Apparently `prog` is a Promise, but I can't handle it at all:

```
try {
	  console.log(1);
	  await prog
	  console.log(2);
} catch (error) {
	  console.log(3);
	  console.log(error)
}
```

This will output just 1, exiting successfully without further errors.

Node 15.

---
Full code: https://github.com/fregante/ghat/blob/ef83253245f6ca40f86349440e64d56123943264/bin.js#L36

You can also try running it directly to see the original error: `npx ghat lukeed/sade/404`

**Comment by fregante** [comment]
It appears that calling `.action` will change what `prog` is, so I guess my problem was misunderstanding that most methods return `prog` but `.action` doesn't.

Solution:

```diff
- const prog = sade(pkg.name + ' <source>', true)
+ const prog = sade(pkg.name + ' <source>', true);
+
+ prog
  	.version(pkg.version)
  	.describe(pkg.description)
```

**Comment by lukeed** [comment]
Hey~! Yea, just to be clear, `parse()` does not return the Sade instance. (I think you have a typo & wrote `action` instead).

This is because you can run Sade is "lazy mode" which gives you the parsed arguments to work with – or the matched action-handler will run, yielding its results.

Your diff should be all that's needed.
