### ISSUE TITLE
First argument is ignored when ran inside a packaged Electron application

### ISSUE THREAD

**Issue by Pumpuli** [lukeed/sade#55]
When using `sade` in an Electron app, the first command line argument is ignored, but only when the Electron app has been built and packaged.

This happens because `process.argv` array content is different in this case. Normally the first element of the array is the NodeJS executable, the second element is the script filename, and only the third element is a relevant CLI argument. This is why the first two elements are always skipped.

    ['node.exe', 'script.js', 'first', 'second', 'third']

However, a packaged Electron app has everything inside the executable, so the relevant CLI arguments start already from the second element of `prcess.argv`:

    ['my_electron_app.exe', 'first', 'second', 'third']

Because `sade` always skips the first two elements, one significant argument gets ignored in this case.

Possible solutions:

- Provide option to set the [`offset`](https://github.com/lukeed/sade/blob/1cdf3e464ca899dcd6e758a50eb82cf7cf484771/src/index.js#L109) to a value other than `2`. Alternatively provide a boolean option which sets `offset` to `1` rather than `2`.
- Auto-detect packaged Electron app. `require('electron').app.isPackaged` is not really viable, since it doesn't work in non-Electron environments. [Yargs](https://github.com/yargs/yargs/blob/561fc7a787228b226e0ba76ab674456cbd30cd37/lib/utils/process-argv.ts) uses `process.versions.electron && !process.defaultApp` to detect argv indices.
- Workaround in user code. Let the user detect Electron environment (E.g. with that `isPackaged`), and insert a dummy element at the beginning of `process.argv` before passing it to `Sade#parse()`.

**Comment by lukeed** [comment]
Sade doesn’t read argv automatically, you pass it in. So because you’re (arguably) in a non-standard/default environment, you should pass in augmented argv when running within an electron env. Because you know when it’s built vs development, you’re in control & know the answer to that question & so can make the swap.
