### ISSUE TITLE
Aliases with multiple characters break things

### ISSUE THREAD

**Issue by jsumners** [lukeed/sade#8]
**foo.js**
```js
const prog = require('sade')('prog')

prog
  .command('foo', 'do foo thing')
  .option('--foobar -fb', 'add foobar thing')

prog.parse(process.argv)
```

```
node foo.js foo --help 

  Description
    do foo thing

  Usage
    $ prog foo [options]

  Options
    -foobar, --fb    add foobar thing
    -h, --help       Displays this message
```

Notice that what should be `--foobar` is `-foobar` and what should be `-fb` is `--fb`.

Additionally:

```js
const prog = require('sade')('prog')

prog
  .command('foo', 'do foo thing')
  .option('--foo-bar -f', 'add foobar thing')

prog.parse(process.argv)
```

```
node foo.js foo --help

  Description
    do foo thing

  Usage
    $ prog foo [options]

  Options
    -f, --foobar    add foobar thing
    -h, --help      Displays this message
```

Notice that what should be `--foo-bar` is `--foobar`.

**Comment by lukeed** [comment]
Hey~! Sorry for the delay 🙈 

For your first point: Aliases are only _meant_ to be single characters. That follows the [Utility Syntax guidline](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html). A `-fb` is actually a shorter way to write `-f -b`.

I'll look into the second report~! That doesn't look right and should be handled.

Thanks!

**Comment by lukeed** [comment]
Yup! Tracking that issue separately. Thank you for pointing this out 🙌
